// ============================================================
// STRANGER ATTRACTIONS — EVENT DATA
// LAST_UPDATED is shown in the site footer — bump it whenever
// the event data changes (ISO 8601 with timezone offset).
// ============================================================

const LAST_UPDATED = "2026-08-08T18:00:20-04:00";
const LAST_CHECKED = "2026-08-09T18:00:22-04:00";

// ============================================================
// To add a show: copy a block below, update the fields, and
// drop the poster image into assets/posters/.
// Past shows are hidden automatically based on the date.
// ============================================================

const EVENTS = [
  {
    headliner: "PARALYSIS",
    support: ["Chemical Dependency", "Graveripper", "Idol Throne"],
    date: "2026-07-24",
    venue: "Black Circle",
    address: "2201 E 46th St, Indianapolis, IN 46205",
    doors: "7:00 PM",
    show: "8:00 PM",
    price: "$20",
    age: "All Ages",
    tickets: "https://www.skeletix.com/4613-stranger-attractions-presents-paralysis/",
    facebook: "https://www.facebook.com/events/2093279531253535/",
    poster: "assets/posters/paralysis.jpg",
    tag: "Thrash (NJ)"
  },
  {
    headliner: "CYBER CRISIS",
    support: ["Dildox", "Healng", "Absolute Form", "Atropa Doll"],
    date: "2026-07-26",
    venue: "State Street Pub",
    address: "243 N State Ave, Indianapolis, IN 46201",
    doors: "7:00 PM",
    show: "8:00 PM",
    price: "$12",
    age: "21 & Over",
    tickets: "https://skeletix.com/4637-stranger-attractions-presents-cyber-crisis/",
    facebook: "",
    poster: "assets/posters/cyber-crisis.jpg",
    tag: ""
  },
  {
    headliner: "TO VIOLENTLY VOMIT",
    support: ["Protrusion", "Scrotal Erosion", "Charybdis"],
    date: "2026-07-30",
    venue: "State Street Pub",
    address: "243 N State Ave, Indianapolis, IN 46201",
    doors: "7:00 PM",
    show: "8:00 PM",
    price: "$16",
    age: "21 & Over",
    tickets: "https://www.skeletix.com/4653-stranger-attractions-presents-to-violently/",
    facebook: "https://www.facebook.com/events/2286035835263934/",
    poster: "assets/posters/to-violently-vomit.jpg",
    tag: "Disgorge US live show"
  },
  {
    headliner: "SIX FEET UNDER",
    support: ["Fuming Mouth", "Flesher", "1 Body 6 Graves"],
    date: "2026-08-14",
    venue: "Black Circle",
    address: "2201 E 46th St, Indianapolis, IN 46205",
    doors: "6:30 PM",
    show: "7:00 PM",
    price: "$25",
    age: "All Ages",
    tickets: "https://www.skeletix.com/4544-stranger-attractions-presents-six-feet-unde/",
    facebook: "https://www.facebook.com/events/2339915919747566/",
    poster: "assets/posters/six-feet-under.jpg",
    tag: "Legendary Death Metal"
  },
  {
    headliner: "REZN",
    support: ["Lume", "Isolation Drills"],
    date: "2026-08-19",
    venue: "Black Circle",
    address: "2201 E 46th St, Indianapolis, IN 46205",
    doors: "7:00 PM",
    show: "8:00 PM",
    price: "$20",
    age: "All Ages",
    tickets: "https://www.skeletix.com/4514-stranger-attractions-presents-rezn-blac/",
    facebook: "https://www.facebook.com/events/1459975292045744/",
    poster: "assets/posters/rezn.jpg",
    tag: "Doom (Chicago, IL)"
  },
  {
    headliner: "HELL IS REAL FEST",
    support: ["Profanatica", "Morbosidad", "Black Altar", "Cloak", "Valdrin", "Poltergeist", "Angel Massacre", "Arsine Ingest"],
    date: "2026-08-22",
    venue: "Black Circle",
    address: "2201 E 46th St, Indianapolis, IN 46205",
    doors: "4:00 PM",
    show: "5:00 PM",
    price: "$30",
    age: "All Ages",
    tickets: "https://skeletix.com/4564-stranger-attractions-presents-hell-is-real/",
    facebook: "",
    poster: "assets/posters/hell-is-real-fest.jpg",
    tag: "Black & Death Metal Fest"
  },
  {
    headliner: "HIPPIE DEATH CULT",
    support: ["The Well", "Moon Destroys", "Ancient Days"],
    date: "2026-09-03",
    venue: "Black Circle",
    address: "2201 E 46th St, Indianapolis, IN 46205",
    doors: "7:00 PM",
    show: "7:30 PM",
    price: "$18",
    age: "All Ages",
    tickets: "https://skeletix.com/4635-stranger-attractions-presents-hippie-death/",
    facebook: "",
    poster: "assets/posters/hippie-death-cult.jpg",
    tag: "Heavy Psych Doom (Portland)"
  },
  {
    headliner: "VEILCASTE",
    support: ["Crop", "Lordship", "Thorr-Axe"],
    date: "2026-09-04",
    venue: "Black Circle",
    address: "2201 E 46th St, Indianapolis, IN 46205",
    doors: "7:00 PM",
    show: "8:00 PM",
    price: "$20",
    age: "All Ages",
    tickets: "https://skeletix.com/4706-veilcaste-record-release-show-black-cir/",
    facebook: "https://www.facebook.com/events/971761605268641/",
    poster: "assets/posters/veilcaste.jpg",
    tag: "“Hellward” Release Show"
  },
  {
    headliner: "FIRES IN THE DISTANCE",
    support: ["Hinayana"],
    date: "2026-09-06",
    venue: "State Street Pub",
    address: "243 N State Ave, Indianapolis, IN 46201",
    doors: "7:00 PM",
    show: "7:30 PM",
    price: "$15",
    age: "21 & Over",
    tickets: "https://skeletix.com/4678-stranger-attractions-presents-fires-in-the/",
    facebook: "",
    poster: "assets/posters/fires-in-the-distance.jpg",
    tag: "Melodic Death Doom (CT)"
  },
  {
    headliner: "NAK’AY",
    support: ["Impulse Noise", "Genestealer", "Thlurm"],
    date: "2026-09-09",
    venue: "Black Circle",
    address: "2201 E 46th St, Indianapolis, IN 46205",
    doors: "7:00 PM",
    show: "8:00 PM",
    price: "$16",
    age: "All Ages",
    tickets: "https://www.skeletix.com/4746-stranger-attractions-presents-nakay-bl/",
    facebook: "",
    poster: "assets/posters/nak-ay-w-impulse-noise-genestealer-thlurm.jpg",
    tag: ""
  },
  {
    headliner: "MONOLORD",
    support: ["Khemmis", "Mother of Graves"],
    date: "2026-09-10",
    venue: "Black Circle",
    address: "2201 E 46th St, Indianapolis, IN 46205",
    doors: "7:00 PM",
    show: "8:00 PM",
    price: "$28",
    age: "All Ages",
    tickets: "https://www.skeletix.com/4414-stranger-attractions-presents-monolord/",
    facebook: "https://www.facebook.com/events/786733734169167/",
    poster: "assets/posters/monolord.jpg",
    tag: "Doom (Sweden)"
  },
  {
    headliner: "CASTLE",
    support: ["Bastard Cross", "Blasted Heath"],
    date: "2026-09-11",
    venue: "Black Circle",
    address: "2201 E 46th St, Indianapolis, IN 46205",
    doors: "7:00 PM",
    show: "8:00 PM",
    price: "$16",
    age: "All Ages",
    tickets: "https://www.skeletix.com/4673-stranger-attractions-presents-castle-bl/",
    facebook: "https://www.facebook.com/events/1585299696551628/",
    poster: "assets/posters/castle.jpg",
    tag: "Heavy Metal (Canada)"
  },
  {
    headliner: "GRAVERIPPER",
    support: ["Raider", "Huntsmen", "Nequient"],
    date: "2026-09-13",
    venue: "State Street Pub",
    address: "243 N State Ave, Indianapolis, IN 46201",
    doors: "7:00 PM",
    show: "",
    price: "$15",
    age: "21 & Over",
    tickets: "",
    facebook: "",
    poster: "assets/posters/graveripper.jpg",
    tag: "No presale — cash at the door"
  },
  {
    headliner: "VOID",
    support: ["Phantom", "Sacred Leather"],
    date: "2026-09-16",
    venue: "Black Circle",
    address: "2201 E 46th St, Indianapolis, IN 46205",
    doors: "7:00 PM",
    show: "8:00 PM",
    price: "$16",
    age: "All Ages",
    tickets: "https://www.skeletix.com/4674-stranger-attractions-presents-void-blac/",
    facebook: "https://www.facebook.com/events/829817206735106/",
    poster: "assets/posters/void.jpg",
    tag: "Thrash (Louisiana)"
  },
  {
    headliner: "LORDS OF THE TRIDENT",
    support: ["Faerie Ring", "Throne of Iron"],
    date: "2026-10-01",
    venue: "Black Circle",
    address: "2201 E 46th St, Indianapolis, IN 46205",
    doors: "7:00 PM",
    show: "8:00 PM",
    price: "$16",
    age: "All Ages",
    tickets: "https://www.skeletix.com/4737-stranger-attractions-presents-lords-of-the/",
    facebook: "",
    poster: "assets/posters/lords-of-the-trident-w-faerie-ring-throne-of-iron.jpg",
    tag: ""
  },
  {
    headliner: "FRIZZI 2 FULCI",
    support: ["Ethan McCarthy"],
    date: "2026-10-07",
    venue: "Holy Ground Studio",
    address: "3317 E 10th St, Indianapolis, IN 46201",
    doors: "7:00 PM",
    show: "8:00 PM",
    price: "$30",
    age: "All Ages",
    tickets: "https://skeletix.com/4670-stranger-attractions-presents-frizzi-2-fulc/",
    facebook: "",
    poster: "assets/posters/frizzi-2-fulci.jpg",
    tag: "Fabio Frizzi Performs Fulci Scores"
  },
  {
    headliner: "SADNESS",
    support: ["Barbelith", "Monterey"],
    date: "2026-10-07",
    venue: "Black Circle",
    address: "2201 E 46th St, Indianapolis, IN 46205",
    doors: "7:00 PM",
    show: "7:30 PM",
    price: "$16",
    age: "All Ages",
    tickets: "https://www.skeletix.com/4697-stranger-attractions-presents-black-circl/",
    facebook: "",
    poster: "assets/posters/sadness.jpg",
    tag: "Atmospheric Black Metal"
  },
  {
    headliner: "EYEHATEGOD",
    support: ["Cavity", "Bl'ast", "Luicidal", "Evil Army"],
    date: "2026-10-10",
    venue: "Black Circle",
    address: "2201 E 46th St, Indianapolis, IN 46205",
    doors: "6:00 PM",
    show: "6:30 PM",
    price: "$35",
    age: "All Ages",
    tickets: "https://www.skeletix.com/4772-stranger-attractions-presents-eyehategod/",
    facebook: "",
    poster: "assets/posters/eyehategod.jpg",
    tag: ""
  },
  {
    headliner: "PSYCROPTIC",
    support: ["Inferi", "Cognitive", "Summoning the Lich"],
    date: "2026-12-04",
    venue: "Black Circle",
    address: "2201 E 46th St, Indianapolis, IN 46205",
    doors: "6:30 PM",
    show: "",
    price: "$25",
    age: "All Ages",
    tickets: "https://www.skeletix.com/4698-stranger-attractions-presents-psycroptic/",
    facebook: "https://www.facebook.com/events/1345150461121456/",
    poster: "assets/posters/psycroptic.jpg",
    tag: "Tech Death (Australia)"
  },
];
